FROM andrius/asterisk:15 

COPY ari.conf /etc/asterisk/ari.conf
COPY extensions.conf /etc/asterisk/extensions.conf
COPY http.conf /etc/asterisk/http.conf
COPY users.conf /etc/asterisk/users.conf

EXPOSE 8088
